# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('word_count', models.CharField(max_length=200)),
                ('density', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='results',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.Keyword'),
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='density',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='url',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='word_count',
        ),
    ]
