# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_auto_20160119_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
