# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_auto_20160119_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('keyword',)},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('url', 'keyword')]),
        ),
    ]
