# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_auto_20160119_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('url', 'keyword')},
        ),
        migrations.AlterField(
            model_name='result',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='result',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='word_count',
            field=models.PositiveIntegerField(),
        ),
    ]
