# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0006_auto_20160119_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='average_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='average_density',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='result',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
