# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0007_auto_20160119_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
