# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0008_keyword_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('keyword', 'url')},
        ),
    ]
